export { default as NavBar } from './slices/NavBar'
export { default as BlogPost } from './slices/BlogPost'
export { default as LandingHero } from './slices/LandingHero'
export { default as FeatureSection } from './slices/FeatureSection'
export { default as CtaSection } from './slices/CtaSection'
export { default as FooterSection } from './slices/FooterSection'
// export { default as ContactForm } from './slices/ContactForm'
// export { default as FaqSection } from './slices/FaqSection'
